import { createElement } from 'lwc';
import Cv_MyResumeExperience from 'c/cv_MyResumeExperience';

describe('c-cv-my-resume-experience', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-cv-my-resume-experience', {
            is: Cv_MyResumeExperience
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});